### PR TITLE
Add ExceptT instances

### PR DESCRIPTION
**Pull request by bergmark**

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks for merging @stepcut! Any chance to get this on stackage soon? This seems to be our only remaining dependency for switching completely to `ExceptT` now :-)

**Comment by stepcut** [comment]
Probably. Because this patch adds new instances, I think I should technically bump the .B component of the version number -- which is a major pain. On the other hand, it only breaks builds that uses orphan instances for ExceptT. So I'm thinking that ignoring the PVP in this case is probably the least overall pain.

Any opinions?

**Comment by bergmark** [comment]
Non-orphan instances is only a C bump nowadays! :-) And anyone defining an orphan instance should have a `== A.B.C.*` dependency. https://wiki.haskell.org/Package_versioning_policy

**Comment by stepcut** [comment]
On hackage now. Sorry about the delay!

**Comment by bergmark** [comment]
thanks!

**Pull request merged**
