### PR TITLE
Compatibility with mtl-2.3

### PR DESCRIPTION
**Pull request by ysangkok**
This bumps dependency requirements, but the new bounds required are still pretty old. I have removed some weird instances, like e.g. `Alternative RqData`.

It still defines Error instances for the mtl releases that have it, but if you would like a cleaner codebase, we could remove all code related to Error or ErrorT.

### CODE REVIEW

**Comment by ysangkok** [comment]
@stepcut Reminder that this needs review. Or would you prefer to wait until GHC actually ships mtl-2.3?

**Comment by stepcut** [comment]
Sorry about the delay -- this just got put on my schedule today. I took a brief look at it before, but I don't understand why the `MonadPlus` and `Alternative` instances got dropped.

**Comment by ysangkok** [comment]
MonadPlus and Alternative have `mzero` and `empty`, but what should these be for RqData, which is polymorphic on its successful parameter? Previously, I think it was using the ErrorT within to get a sketchy instance, such that `empty` for a RqData would get you an unsuccessful RqData with no actual error inside. This seems nonsensical, and made me think it would be better to just remove the instance.

**Comment by stepcut** [comment]
Ahoy! Sorry this is taking a while. It is not that I don't care -- it is that I care a lot, but I am super busy at the moment. I've got GHC 9.3 installed, but still trying to get all the dependencies installed.

I need to convince myself that dropping `MonadPlus` and `Alternative` is the best option.

**Comment by ysangkok** [comment]
> I've got GHC 9.3 installed

Just curious, but why? I don't know how to check this definitively, but it doesn't seem like any version of GHC ships mtl 2.3 according to [the GHC gitlab wiki](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history).

The way I test this is using `cabal build --constraint='transformers>=0.6' --constraint='mtl>=2.3'` which works even with versions of GHC that don't ship mtl 2.3 (they ship another version). E.g. GHC 8.10.7 or 9.2.3.

**Comment by stepcut** [comment]
Aha. I tried to use `cabal2nix` to get `mtl-2.3` and that did not work. But obviously, I should have just used `cabal` directly.

It seems like there are a lot of changes that `RqData` that go beyond what is required to upgrade to mtl 2.3. Shouldn't this be sufficient?

```
diff --git a/src/Happstack/Server/RqData.hs b/src/Happstack/Server/RqData.hs
index 89dd38e..e3657de 100644
--- a/src/Happstack/Server/RqData.hs
+++ b/src/Happstack/Server/RqData.hs
@@ -1,4 +1,4 @@
-{-# LANGUAGE DeriveDataTypeable, GeneralizedNewtypeDeriving, FlexibleContexts, FlexibleInstances, MultiParamTypeClasses #-}
+{-# LANGUAGE CPP, DeriveDataTypeable, GeneralizedNewtypeDeriving, FlexibleContexts, FlexibleInstances, MultiParamTypeClasses #-}
 -- | Functions for extracting values from the query string, form data, cookies, etc.
 --
 -- For in-depth documentation see the following section of the Happstack Crash Course:
@@ -67,7 +67,11 @@ import qualified Control.Monad.Writer.Lazy as Lazy     (WriterT, mapWriterT)
 import qualified Control.Monad.Writer.Strict as Strict (WriterT, mapWriterT)
 import qualified Control.Monad.RWS.Lazy as Lazy        (RWST, mapRWST)
 import qualified Control.Monad.RWS.Strict as Strict    (RWST, mapRWST)
+#if MIN_VERSION_mtl(2,3,0)
+import Control.Monad.Trans.Error
+#else
 import Control.Monad.Error                      (Error(noMsg, strMsg), ErrorT, mapErrorT)
+#endif
 import Control.Monad.Trans                      (MonadIO(..), lift)
 import Control.Monad.Trans.Except               (ExceptT, mapExceptT)
 import qualified Data.ByteString.Char8          as P
```

In addition to dropping the `MonadPlus` and `Alternative` instances, your patch also changes the behavior of the `Applicative` instance. Now, it can be argued that the current behavior of the `Applicative` instance is wrong and should be changed. But that seems like a different issue.

With your change, in the following example, only the first missing parameter is reported, instead of both missing parameters.

https://www.happstack.com/docs/crashcourse/index.html#using-the-rqdata-for-better-error-reporting

That is because the documented behavior relies on '<*>` and `ap.` behaving differently. But the Haskell overlords eventually declared that `<*>` and `ap` should do the exact same thing. So.. that means that we would need a separate `RqDataA` which only has an `Applicative` instance.

Making that change would silently change the behavior of any code that relies on the currently useful, but theoretically broken behavior. 

https://www.reddit.com/r/haskell/comments/3v9qlf/why_must_ap/

**Comment by ysangkok** [comment]
@stepcut I have reintroduced the removed Applicative instance, and I have added a test that verifies that its use accumulates all errors.

The MonadPlus/Alternative instances are still missing, would you like to have their instances retained also? I could use a similar approach with tests asserting that the behavior matches.

**Comment by stepcut** [comment]
I will look at this in the next couple days. Did you see this pull request?

https://github.com/ysangkok/happstack-server/pull/1

**Comment by ysangkok** [comment]
Oops, I had somehow missed that. I have tested it and it seems to have the same behavior on mtl-2.3 and mtl-2.2.3. Looks good to me!

**Comment by stepcut** [comment]
Uploaded as happstack-7.8.0 on hackage. Big thanks to you for making this happen!

**Comment by andreasabel** [comment]
@stepcut @ysangkok : I get a build failure for `happstack-7.8.0.1` with `mtl-2.3.1`:
```
$ cabal build -c 'mtl >= 2.3'
Build profile: -w ghc-9.4.4 -O1
In order, the following will be built (use -v for more details):
 - happstack-server-7.8.0.1 (lib) (first run)
...
[21 of 35] Compiling Happstack.Server.RqData ( src/Happstack/Server/RqData.hs, /Users/abel/tmp/happstack-server-7.8.0.1/dist-newstyle/build/x86_64-osx/ghc-9.4.4/happstack-server-7.8.0.1/build/Happstack/Server/RqData.o, /Users/abel/tmp/happstack-server-7.8.0.1/dist-newstyle/build/x86_64-osx/ghc-9.4.4/happstack-server-7.8.0.1/build/Happstack/Server/RqData.dyn_o ) [Control.Monad.Trans package changed]

src/Happstack/Server/RqData.hs:186:31: error:
    • No instance for (Control.Monad.Trans.Error.Error (Errors String))
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (MonadPlus RqData)
    |
186 |     deriving (Functor, Monad, MonadPlus, Applicative, Alternative, MonadReader RqEnv )
    |                               ^^^^^^^^
```
Similar complaint about the `Alternative` derivation in this line.

I see you discussed the issue above.  Apparently, restoring these instances blew the project.
The catch is that `tranformers >= 0.6` is not forced by `mtl >= 2.3`, and since I only supplied the constraint `mtl >= 2.3`, compilation broke.  (Compilation succeeds with both of these constraints supplied.)

Dunno, I see `#if` for both `mtl` and `transformers` in [`44fe428` (#74)](https://github.com/Happstack/happstack-server/pull/74/commits/44fe428cdcfe37ecdef3cd96c1f1bc1e64d166d4), so maybe these have to be restructured.

**Pull request merged**
