### PR TITLE
Add support for parameter following filename

### PR DESCRIPTION
**Pull request by bugthunk**
...in `content-disposition` multipart field

### CODE REVIEW

**Comment by stepcut** [comment]
Can you provide an example of something that doesn't parse correctly before this patch, but does afterwards?

**Comment by bugthunk** [comment]
Sure. First we use the old `p_parameter`:
```
ghci> let doesNotWorkWithOldParserButWithNew = "form-data; filename=\"file.pdf\"; name=\"file\""
ghci> parseContentDisposition doesNotWorkWithOldParserButWithNew
ContentDisposition "form-data" [("filename","file.pdf\"; name=\"file")]
```
As expected it eats the whole string after `filename`, backslashes and all. This is a real-life example we have of a client's code that should work, but does not.

Now, the new:
```
ghci> let doesNotWorkWithOldParserButWithNew = "form-data; filename=\"file.pdf\"; name=\"file\""
ghci> parseContentDisposition doesNotWorkWithOldParserButWithNew
ContentDisposition "form-data" [("filename","file.pdf"),("name","file")]
```

Note that should the `lookAhead` fail (i.e. it is not possible to parse another param) the code behaves as before.

If this is merged it will not be possible to name a file e.g. `some_file_name"; name="value".txt` anymore, since it will be able to parse a param `name` from this. I hope the universe can live with this, but who knows.

**Comment by bugthunk** [comment]
@stepcut did you see the example above?

**Comment by stepcut** [comment]
I did. Now I need time to think about it. Looking a `pContentDisposition`,

```
pContentDisposition :: Parser ContentDisposition
pContentDisposition =
  do void $ many ws1
     c_cd <- p_token
     c_parameters <- many p_parameter
     return $ ContentDisposition (map toLower c_cd) c_parameters
```

It seems like it should already be handling multiple parameters fine. But it doesn't because of the work around here,

https://github.com/Happstack/happstack-server/blob/master/src/Happstack/Server/Internal/RFC822Headers.hs#L93

But.. that workaround is more than 11 years old. Do browsers actually escape things correctly now? Perhaps the right solution is to remove the `buggyLiteralString` bit entirely?

**Comment by bugthunk** [comment]
Since I am quite unable to find any information about whether browsers escape correctly or not nowadays, let me make..._A Most Humble Suggestion_: We could merge this so that it actually works (we have some real problems with it at $WORK) and I could try to test the major browsers going backwards to see in which version - if at all - the bug was fixed.

**Comment by bugthunk** [comment]
May I also add that since information about current browsers really isn't readily available it's a safer bet to merge this PR? I do realise I am promoting myself which I really hate, but in this instance I think it's for the better. For instance, we have enterprise customers still running Internet Explorer 9. I do not know whether this particular browser behaves well or not, so I would based on this really advise against removing the `buggyLiteralString` entirely. We may be forced to fork Happstack otherwise which none of us want.

**Comment by stepcut** [comment]
On the one hand, I am not thrilled about adding another arbitrary hack to the parser with no specification. On the other hand, it seems that it is time to de a major overhaul of the Content-Disposition stuff to support the latest RFCs.

I am also not wild about the use of `lookAhead` but this is a rarely used code path and shouldn't really affect performance in a meaningful way.

So, given the minimal impact of this patch, I am going to pull it, and then open a new bug to update the parsing to modern standards with a test suite.

**Pull request merged**
